language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby
  - jruby-head
  - ree

notifications:
  email:
    on_success: never

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script: "bundle exec rake"
